Lesson9
alex-rns/magento-226 pull request #9
Opened 2018-12-13 14:46 UTC by alex-rns

### Description

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-08 18:40 UTC, APanteleychuk requested changes
Need to fix

2019-01-08 18:40 UTC, APanteleychuk commented on app/code/BelodubrovskyiAn/CustomWidget/view/frontend/templates/widget/lesson9_banner.phtml
> +    <?php if ($block->getData('block_id')) : ?>
Please use set/get methods getTitle() etc.

2019-01-08 18:40 UTC, APanteleychuk commented on app/code/BelodubrovskyiAn/CustomWidget/view/frontend/templates/widget/lesson9_banner.phtml
> +        <?php echo $block->getLayout()
Needs to be moved in block like function.

2019-01-10 11:22 UTC, alex-rns commented on app/code/BelodubrovskyiAn/CustomWidget/view/frontend/templates/widget/lesson9_banner.phtml
> +    <?php if ($block->getData('block_id')) : ?>
Fixed.

2019-01-16 19:00 UTC, merged